### ISSUE TITLE
云函数关闭探索提醒时仍旧会发起提醒

### ISSUE THREAD

**Issue by a492338462** [Xm798/Genshin-Dailynote-Helper#30]
### 问题描述

_**_config.yaml参数_**_
```yaml
# 探索派遣完成提醒，true or false
  # Expeditions completion reminder, true or false
  EXPEDITION_NOTICE: false
  # 是否等全部探索派遣都完成后才发送提醒，true or false
  # Whether to wait until all expeditions are completed before sending reminders，true or false
  WAIT_ALL_EXPEDITION: false
**configdata.py参数**
 EXPEDITION_NOTICE: StrictBool = False
    WAIT_ALL_EXPEDITION: StrictBool = False
```
**测试结果**
⏩︎未到每日委托检查提醒时间。
✅树脂检查结束，当前树脂15，未到提醒临界值。
✅洞天宝钱检查结束，未溢出。
⏩︎未开启探索派遣完成提醒，已跳过。
✅参量质变仪未准备好。

设置上是关闭探索提醒的，但实际依旧会每半小时发送探索完成的提醒推送

### 运行环境

云函数

### 程序版本

v2.1.7

### 复现流程

```yaml
# 接收提醒设置
# Receive reminder settings
receive_notice:
  # 原粹树脂提醒阈值，填 0 则关闭提醒
  # The original resin reminder threshold, fill in 0 to close the reminder
  RESIN_THRESHOLD: 140
  # 委托未完成的提醒时间，不填则关闭提醒
  # Reminder time when the commissions are not completed, if not filled, the reminder will be closed
  COMMISSION_NOTICE_TIME: '21:00'
  # 探索派遣完成提醒，true or false
  # Expeditions completion reminder, true or false
  EXPEDITION_NOTICE: false
  # 是否等全部探索派遣都完成后才发送提醒，true or false
  # Whether to wait until all expeditions are completed before sending reminders，true or false
  WAIT_ALL_EXPEDITION: false
  # 洞天宝钱溢出提醒，true or false
  # Homecoin overflow reminder，true or false
  HOMECOIN_NOTICE: true
  # 洞天宝钱提醒的阈值，为最大存储上限×该值，该值为 0 到 1 之间的数字
  # The threshold of Homecoin, which is the maximum storage upper limit × this value. A number between 0 and 1.
  HOMECOIN_THRESHOLD: 0.95
  # 参量质变仪就绪提醒
  # Parametric Transformer status reminder, true or false
  TRANSFORMER: true

time:
  # 检查间隔（分钟），云函数运行时请确保与触发器设置一致，以便执行睡前检查
    # Check interval (minutes)
  CHECK_INTERVAL: 30
  # 免打扰时间
  # Do Not Disturb Time
  SLEEP_TIME: '23:00-07:00'
```

### 完整日志

```shell
执行日志
START RequestId: 86f3375a-60a3-4906-95e5-a04dc8f40cfb


-------------------------------------------------------------

|                Genshin Dailynote Helper                   |

-------------------------------------------------------------

| Current Version: 2.1.7                                    |

| Last Update: Mar 31, 2022                                 |

| Github: https://github.com/Xm798/Genshin-Dailynote-Helper |

-------------------------------------------------------------


🗝️ 当前配置了1个账号，正在执行第1个

-------------------------

正在获取角色信息

Starting new HTTPS connection (1): api-takumi.mihoyo.com:443

https://api-takumi.mihoyo.com:443 "GET /binding/api/getUserGameRolesByCookie?game_biz=hk4e_cn HTTP/1.1" 200 204

获取到国服的1个角色...

第1个角色，109007684 丫丫

Starting new HTTPS connection (1): api-takumi.mihoyo.com:443

https://api-takumi.mihoyo.com:443 "GET /game_record/app/genshin/api/dailyNote?role_id=109007684&server=cn_gf01 HTTP/1.1" 200 480

⏩︎未到每日委托检查提醒时间。

✅树脂检查结束，当前树脂18，未到提醒临界值。

✅洞天宝钱检查结束，未溢出。

⏩︎未开启探索派遣完成提醒，已跳过。

✅参量质变仪未准备好。

-------------------------

本轮运行结束，等待下次检查...

Response RequestId: 86f3375a-60a3-4906-95e5-a04dc8f40cfb RetMsg: null

END RequestId: 86f3375a-60a3-4906-95e5-a04dc8f40cfb

Report RequestId: 86f3375a-60a3-4906-95e5-a04dc8f40cfb Duration: 638ms Memory: 64MB MemUsage: 22.40MB
```

### 其他补充说明

无
